[alias]
run-wasm = ["run", "--release", "--package", "run-wasm", "--"]

# Using unstable APIs is required for writing to clipboard
[target.wasm32-unknown-unknown]
rustflags = ["--cfg=web_sys_unstable_apis"]
